/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miJuego;

import java.awt.Color;
import javax.swing.JButton;

public class VentanaJuego extends javax.swing.JFrame {

    enum enTurno { cruz, circulo };
    enTurno turno = enTurno.cruz;
    JButton botones[] = new JButton[10];
    clickEnBoton click;
    boolean jugando = true;

    /**
     * Creates new form VentanaJuego
     */
    public VentanaJuego() {
        initComponents();
        click = new clickEnBoton(this);
        botones[1] = btn1;
        botones[2] = btn2;
        botones[3] = btn3;
        botones[4] = btn4;
        botones[5] = btn5;
        botones[6] = btn6;
        botones[7] = btn7;
        botones[8] = btn8;
        botones[9] = btn9;
        
        for (int i =1; i<=9; i++) {
            botones[i].addActionListener(click);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNuevo = new javax.swing.JMenu();
        mnuNuevo2 = new javax.swing.JMenuItem();
        mnuMensaje = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Gato");
        setMinimumSize(new java.awt.Dimension(252, 200));
        setPreferredSize(new java.awt.Dimension(252, 250));
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));
        getContentPane().add(btn1);
        getContentPane().add(btn2);
        getContentPane().add(btn3);
        getContentPane().add(btn4);
        getContentPane().add(btn5);
        getContentPane().add(btn6);
        getContentPane().add(btn7);
        getContentPane().add(btn8);
        getContentPane().add(btn9);

        mnuNuevo.setText("Nuevo Juego");
        mnuNuevo.setToolTipText("");

        mnuNuevo2.setText("Nuevo");
        mnuNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevo2ActionPerformed(evt);
            }
        });
        mnuNuevo.add(mnuNuevo2);

        jMenuBar1.add(mnuNuevo);

        mnuMensaje.setText("Inicia Cruz");
        mnuMensaje.setEnabled(false);
        jMenuBar1.add(mnuMensaje);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevo2ActionPerformed
        mnuMensaje.setText("Inicia Cruz");
        turno = enTurno.cruz;
        for (int i = 1; i <= 9; i++) {
            botones[i].setText("");
            botones[i].setBackground(null);
        }
        jugando = true;
    }//GEN-LAST:event_mnuNuevo2ActionPerformed

    void tirada(int posicion) {
        // realiza una tirada 
        if (jugando) {

            //Coloca la marca
            if (turno == enTurno.cruz) {
                botones[posicion].setText("X");
                turno = enTurno.circulo;
            } else {
                botones[posicion].setText("O");
                turno = enTurno.cruz;
            }

            //Despliega el mensaje del turno siguiente
            if (turno == enTurno.circulo) {
                mnuMensaje.setText("Turno siguiente: Circulo");
            } else {
                mnuMensaje.setText("Turno siguiente: Cruz");
            }

            //Verifica si se cumple con alguna condición de ganar
            switch (posicion) {

                case 1:
                    //Con 2,3  4,7  y  5,9
                    if (valida(1, 2, 3) || valida(1, 4, 7) || valida(1, 5, 9)) {
                        jugando = false;
                    }
                    break;

                case 2:
                    //con 1,3 y 5,8
                    if (valida(2, 1, 3) || valida(2, 5, 8)) {
                        jugando = false;
                    }
                    break;

                case 3:
                    //Con 1,2  6,9  y  5,7
                    if (valida(3, 1, 2) || valida(3, 6, 9) || valida(3, 5, 7)) {
                        jugando = false;
                    }
                    break;

                case 4:
                    //1,7 y 5,6
                    if (valida(4, 1, 7) || valida(4, 5, 6)) {
                        jugando = false;
                    }
                    break;

                case 5:
                    //2,8  4,6  1,9  7,3
                    if (valida(5, 2, 8) || valida(5, 4, 6)
                            || valida(5, 1, 9) || valida(5, 7, 3)) {
                        jugando = false;
                    }
                    break;

                case 6:
                    //3,9 y 4,5
                    if (valida(6, 3, 9) || valida(6, 4, 5)) {
                        jugando = false;
                    }
                    break;

                case 7:
                    // 1,4  8,9  5,3
                    if (valida(7, 1, 4) || valida(7, 8, 9) || valida(7, 5, 3)) {
                        jugando = false;
                    }
                    break;

                case 8:
                    //2,5  7,9
                    if (valida(8, 2, 5) || valida(8, 7, 9)) {
                        jugando = false;
                    }
                    break;

                case 9:
                    //1,5  7,8  3,6
                    if (valida(9, 1, 5) || valida(9, 7, 8) || valida(9, 3, 6)) {
                        jugando = false;
                    }
                    break;
            }
        }
    }

    boolean valida(int tirada, int primero, int segundo) {
        //Valida si las posiciones donde se hace la tirada y los otros dos botones 
        //tienen el mismo texto (Equis o O)
        if (botones[primero].getText().equals(botones[tirada].getText())
                && botones[segundo].getText().equals(botones[tirada].getText())) {

            System.out.println("Ya ganó");

            botones[tirada].setBackground(Color.green);
            botones[primero].setBackground(Color.green);
            botones[segundo].setBackground(Color.green);

            if (botones[tirada].getText().equals("X")) {
                mnuMensaje.setText("Ganó: Cruz");
            } else {
                mnuMensaje.setText("Ganó: Circulo");
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuMensaje;
    private javax.swing.JMenu mnuNuevo;
    private javax.swing.JMenuItem mnuNuevo2;
    // End of variables declaration//GEN-END:variables

}
